# docker-compose.yaml
  version: '3.8'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      container_name: jenkins
      restart: always
      networks:
        - proxy
      volumes:
        - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.jen.rule=Host(`jenkins.yuri.sk`)"
        - "traefik.http.routers.jen.service=jen"
        - "traefik.http.services.jen.loadbalancer.server.port=8080"
        - "traefik.http.routers.jen.tls=true"
        - "traefik.http.routers.jen.tls.certresolver=letsencrypt"
  networks:
    proxy:
      external: true

